//
// Created by dallin on 8/17/20.
//

#pragma once

#define KRISPY_MOUSE_BUTTON_1         0
#define KRISPY_MOUSE_BUTTON_2         1
#define KRISPY_MOUSE_BUTTON_3         2
#define KRISPY_MOUSE_BUTTON_4         3
#define KRISPY_MOUSE_BUTTON_5         4
#define KRISPY_MOUSE_BUTTON_6         5
#define KRISPY_MOUSE_BUTTON_7         6
#define KRISPY_MOUSE_BUTTON_8         7
#define KRISPY_MOUSE_BUTTON_LAST      KRISPY_MOUSE_BUTTON_8
#define KRISPY_MOUSE_BUTTON_LEFT      KRISPY_MOUSE_BUTTON_1
#define KRISPY_MOUSE_BUTTON_RIGHT     KRISPY_MOUSE_BUTTON_2
#define KRISPY_MOUSE_BUTTON_MIDDLE    KRISPY_MOUSE_BUTTON_3